#!/bin/bash

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AppArmor profiles in live mode need the following line to work
## but because of a bug in AppArmor, this breaks reloading profiles
## so it is only enabled in live mode.
## https://forums.whonix.org/t/error-values-added-to-a-non-existing-variable-homedirs-rw-home-in-tunables-home-d-live-mode/8065
## https://forums.whonix.org/t/live-mode-etc-apparmor-d-tunables-home-d-live-mode-breaks-aa-enforce/5868
## https://bugs.launchpad.net/apparmor/+bug/1331856
## https://bugs.launchpad.net/apparmor/+bug/1387775

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

true "$0: START"

## sets: live_status_detected
# shellcheck source=../../../helper-scripts/usr/libexec/helper-scripts/live-mode.sh
source "${HELPER_SCRIPTS_PATH:-}"/usr/libexec/helper-scripts/live-mode.sh

## Assigned by the sourced live-mode.sh above.
# shellcheck disable=SC2154

if [ "${live_status_detected}" = 'true' ]; then
   ## Live Mode.

   ## Idempotence.
   ## Allow to disable this feature by using double hash ('##').
   if grep --quiet -- "^#@{HOMEDIRS}+=/rw/home/" /etc/apparmor.d/tunables/home.d/live-mode ; then
      str_replace "#@{HOMEDIRS}+=/rw/home/" "@{HOMEDIRS}+=/rw/home/" /etc/apparmor.d/tunables/home.d/live-mode
   fi
else
   ## Persistent Mode.

   ## Idempotence.
   ## grep to see if it is enabled (not commented out) before str_replace
   ## adding a hash ('#') in front of it to avoid adding multiple hashes in
   ## front of it.
   if grep --quiet -- "^@{HOMEDIRS}+=/rw/home/" /etc/apparmor.d/tunables/home.d/live-mode ; then
      str_replace "@{HOMEDIRS}+=/rw/home/" "#@{HOMEDIRS}+=/rw/home/" /etc/apparmor.d/tunables/home.d/live-mode
   fi
fi

true "$0: END"
